import * as THREE from 'three'

export const SOLIDS = [
  {
    id: 'tetrahedron',
    nameKo: '정사면체',
    nameEn: 'Tetrahedron',
    element: '불 (Fire)',
    faces: 4,
    edges: 6,
    vertices: 4,
    color: '#ff00cc',
    accentColor: '#ff88ff',
    geometry: () => new THREE.TetrahedronGeometry(2.4, 0),
  },
  {
    id: 'cube',
    nameKo: '정육면체',
    nameEn: 'Cube',
    element: '땅 (Earth)',
    faces: 6,
    edges: 12,
    vertices: 8,
    color: '#00ccff',
    accentColor: '#88eeff',
    geometry: () => new THREE.BoxGeometry(3.4, 3.4, 3.4),
  },
  {
    id: 'octahedron',
    nameKo: '정팔면체',
    nameEn: 'Octahedron',
    element: '공기 (Air)',
    faces: 8,
    edges: 12,
    vertices: 6,
    color: '#00ff88',
    accentColor: '#88ffcc',
    geometry: () => new THREE.OctahedronGeometry(2.6, 0),
  },
  {
    id: 'dodecahedron',
    nameKo: '정십이면체',
    nameEn: 'Dodecahedron',
    element: '우주 (Cosmos)',
    faces: 12,
    edges: 30,
    vertices: 20,
    color: '#ffcc00',
    accentColor: '#ffe066',
    geometry: () => new THREE.DodecahedronGeometry(2.4, 0),
  },
  {
    id: 'icosahedron',
    nameKo: '정이십면체',
    nameEn: 'Icosahedron',
    element: '물 (Water)',
    faces: 20,
    edges: 30,
    vertices: 12,
    color: '#aa44ff',
    accentColor: '#cc88ff',
    geometry: () => new THREE.IcosahedronGeometry(2.5, 0),
  },
]
